# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNzVC-yHVuhgTIHDUWvNe1oZW-ITTQt5
"""
from wordle_core import vocabulary
# Training hyperparameters
NUM_EPISODES = 5000
GAMMA = 0.99
LR = 0.0005
EVAL_EVERY = 200
EVAL_EPISODES = 100
ENTROPY_COEF = 0.01

# Model architecture
HIDDEN_DIM = 512
INPUT_DIM = 725

# Paths
SAVE_PATH = "pure_rl_wordle_a2c.pth"
VOCAB_PATH = "/content/drive/MyDrive/Colab Notebooks/wordle_actual.txt"
SOLUTIONS_PATH = "/content/drive/MyDrive/Colab Notebooks/wordle-solution-list.txt"

# Device
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")