# -*- coding: utf-8 -*-
"""wordle_core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1fPVuvjjOd3ZJF9CE8XYTRFZpd55jJs
"""

import random
from collections import Counter

def vocabulary(vocab_path, solutions_path):
    """
    - Uses ALL allowed guesses (12k words) 
    - Solutions (2.3k words) are only used as targets
    """
    try:
        # Load SOLUTION words (targets only)
        with open(solutions_path, 'r') as f:
            solutions = [w.strip().lower() for w in f if len(w.strip()) == 5]

        # Load ALLOWED guesses (full vocabulary)
        with open(vocab_path, 'r') as f:
            allowed = [w.strip().lower() for w in f if len(w.strip()) == 5]

        full_vocab = allowed
        VOCAB_SIZE = len(full_vocab)
        WORD_TO_IDX = {w: i for i, w in enumerate(full_vocab)}

        print("VOCABULARY:")
        print(f"   Solutions: {len(solutions)} words (targets only)")
        print(f"   Allowed guesses: {len(allowed)} words (full action space)")
        print(f"   Training vocabulary: {VOCAB_SIZE} words")

        return full_vocab, solutions, VOCAB_SIZE, WORD_TO_IDX

    except Exception as e:
        print(f"Error loading files: {e}")
        # Fallback vocabulary
        solutions = ["apple", "house", "water", "light", "stone"]
        allowed = solutions + ["salet", "crate", "trace", "adieu", "soare"]
        full_vocab = allowed
        VOCAB_SIZE = len(full_vocab)
        WORD_TO_IDX = {w: i for i, w in enumerate(full_vocab)}
        return full_vocab, solutions, VOCAB_SIZE, WORD_TO_IDX

def wordle_feedback(guess: str, target: str):
    """Calculate Wordle feedback for guess against target"""
    guess, target = guess.lower(), target.lower()
    result = [0] * 5
    target_letters = Counter(target)

    # First pass: mark greens
    for i in range(5):
        if guess[i] == target[i]:
            result[i] = 2
            target_letters[target[i]] -= 1

    # Second pass: mark yellows
    for i in range(5):
        if result[i] == 0 and target_letters.get(guess[i], 0) > 0:
            result[i] = 1
            target_letters[guess[i]] -= 1

    return tuple(result)

def is_consistent(history, candidate):
    """Check if candidate word is consistent with game history"""
    return all(wordle_feedback(g, candidate) == fb for g, fb in history)