# -*- coding: utf-8 -*-
"""wordle_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGdS1IL5yinqZdKPMxzBByYsMupesIFU
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class WordleA2CNet(nn.Module):
    def __init__(self, input_dim, vocab_size, hidden_dim=512):
        super().__init__()

        self.feature_extractor = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(0.2),
        )

        self.actor = nn.Sequential(
            nn.Linear(hidden_dim // 2, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, vocab_size)
        )

        self.critic = nn.Sequential(
            nn.Linear(hidden_dim // 2, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        features = self.feature_extractor(x)
        logits = self.actor(features)
        value = self.critic(features).squeeze(-1)
        return logits, value

def masked_softmax(logits, mask, episode, total_episodes):
    adaptive_temp = max(0.3, 1.5 - (episode / total_episodes) * 1.2)
    logits = logits / max(adaptive_temp, 1e-6)
    logits = logits.masked_fill(mask == 0, -1e9)
    return F.softmax(logits, dim=-1), adaptive_temp